name: demo-app-action
description: This is an action to assign yourself to issue for a rep 
author: skbhati199
branding:
  icon: 'thumbs-up'
  color: 'white'

inputs:
  message:
    description: 'Message to prospective contributro'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - 
      run: |
        BODY="$(jq '.comment.body' $GITHUB_EVENT_PATH)"
        ISSUE_NUMBER="$(jq '.issue.number' $GITHUB_EVENT_PATH)"
        LOGIN="$(jq '.comment.user.login' $GITHUB_EVENT_PATH | tr -d \")"
        REPO="$(jq '.repository.full_name' $GITHUB_EVENT_PATH | tr -d \")"
        if [[ $BODY == *".take"* ]]; then
          echo "Assigning issue $ISSUE_NUMBER to $LOGIN"
          echo "Using the link: https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/assignees"
          curl -H "Authorization: token $GITHUB_TOKEN" -d '{"assignees":["'"$LOGIN"'"]}' https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/assignees
          if [[ ! -z $INPUT_MESSAGE ]]; then
            jq -n -r --arg body "$INPUT_MESSAGE" '{body: $body}' > payload.json
            curl -X POST -H "Authorization: token $GITHUB_TOKEN" --data @payload.json https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/comments
          fi
        fi
      shell: bash
      env:
        INPUT_MESSAGE: "${{ inputs.message }}"
